### PR TITLE
Fixed error I started getting with slower connections, and added error to notification.

### PR DESCRIPTION
**Pull request by tgrrr**

### CODE REVIEW

**Comment by tgrrr** [comment]
@MikoMagni this code isn't functional but I'm getting some errors with my [last PR](https://github.com/MikoMagni/Alfred-for-Trello/pull/15) on some networks. Does it need refactoring?

**Comment by MikoMagni** [comment]
@tgrrr I haven't had a chance to test it. Would you like me to merge your latest change?

**Comment by tgrrr** [comment]
@MikoMagni yes thanks

**Comment by MikoMagni** [comment]
@tgrrr done :)

**Comment by tgrrr** [comment]
Thanks

**Pull request merged**
